/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.web;

import com.smart.cons.CommonConstant;
import com.smart.dao.Page;
import com.smart.domain.Board;
import com.smart.domain.Post;
import com.smart.domain.Topic;
import com.smart.domain.User;
import com.smart.service.ForumService;
import com.smart.serviceinterfaces.ForumServiceInterface;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import java.util.Date;

/**
 *   这个Action负责处理论坛普通操作功能的请求，包括：显示论坛版块列表、显示论坛版块主题列表、
 * 表主题帖、回复帖子、删除帖子、设置精华帖子等操作。
 */
@Controller
public class BoardManageController extends BaseController {

	private ForumServiceInterface forumService;

	@Autowired
	@Qualifier("redisForumService")
	public void setForumService(ForumServiceInterface forumService) {
		this.forumService = forumService;
	}

	/**
	 * 列出论坛模块下的主题帖子
	 * 
	 * @param boardId
	 * @return
	 */
	@RequestMapping(value = "/boards/{boardId}", method = RequestMethod.GET)
	//url换成restful风格应该类似 board/BoardTopics/{boardId}
	public ModelAndView listBoardTopics(@PathVariable Integer boardId,@RequestParam(value = "pageNo", required = false) Integer pageNo) {
		ModelAndView view =new ModelAndView();
		Board board = forumService.getBoardById(boardId);
		pageNo = pageNo==null?1:pageNo;
		Page pagedTopic = forumService.getPagedTopics(boardId, pageNo,
				CommonConstant.PAGE_SIZE);
		view.addObject("board", board);
		view.addObject("pagedTopic", pagedTopic);
		view.setViewName("/listBoardTopics");
		return view;
	}

	/**
	 * 删除版块
	 */
	@RequestMapping(value = "/boards/{boardIds}", method = RequestMethod.DELETE)
	public String removeBoard(@PathVariable String boardIds) {
		String[] arrIds = boardIds.split(",");
		for (int i = 0; i < arrIds.length; i++) {
			forumService.removeBoard(new Integer(arrIds[i]));
		}
		String targetUrl = "/index.html";
		return "redirect:"+targetUrl;
	}

	/**
	 * 添加主题帖页面
	 * 
	 * @param boardId
	 * @return
	 */
	//@RequestMapping(value = "/board/addTopicPage-{boardId}", method = RequestMethod.GET)
	@RequestMapping(value = "/boards/{boardId}/topics", method = RequestMethod.POST)
	///board/{boardId}/TopicPage http方法是post
	public ModelAndView addTopicPage(@PathVariable Integer boardId) {
		ModelAndView view =new ModelAndView();
		view.addObject("boardId", boardId);
		view.setViewName("/addTopic");
		return view;
	}

	/**
	 * 添加一个主题帖
	 * 
	 * @param request
	 * @param topic
	 * @return
	 */
	@RequestMapping(value = "/board/addTopic", method = RequestMethod.POST)
	public String addTopic(HttpServletRequest request,Topic topic) {
		User user = getSessionUser(request);
		topic.setUser(user);
		Date now = new Date();
		topic.setCreateTime(now);
		topic.setLastPost(now);
		forumService.addTopic(topic);
		String targetUrl = "/boards/" + topic.getBoardId();
		return "redirect:"+targetUrl;
	}

	/**
	 * 列出主题的所有帖子
	 * 
	 * @param topicId
	 * @return
	 */
	@RequestMapping(value = "/boards/{boardId}/topics/{topicId}", method = RequestMethod.GET)
	public ModelAndView listTopicPosts(@PathVariable Integer topicId,@RequestParam(value = "pageNo", required = false) Integer pageNo,@PathVariable String boardId) {
		ModelAndView view =new ModelAndView();
		Topic topic = forumService.getTopicByTopicId(topicId);
		pageNo = pageNo==null?1:pageNo;
		Page pagedPost = forumService.getPagedPosts(topicId, pageNo,
				CommonConstant.PAGE_SIZE);
		// 为回复帖子表单准备数据
		view.addObject("topic", topic);
		view.addObject("pagedPost", pagedPost);
		view.setViewName("/listTopicPosts");
		return view;
	}

	/**
	 * 回复主题
	 * 
	 * @param request
	 * @param post
	 * @return
	 */
	@RequestMapping(value = "/boards/{boardId}/topics/{topicIds}", method = RequestMethod.POST)
	public String addPost(HttpServletRequest request, Post post,@PathVariable String topicIds,@PathVariable String boardId) {
		post.setCreateTime(new Date());
		post.setUser(getSessionUser(request));
		Topic topic = new Topic();
		int topicId = Integer.valueOf(request.getParameter("topicId"));//jsp listTopicPosts那里请求参数 topic.topicId 自己改成 topicId 就对了
		//
		if (topicId >0) {
			topic.setTopicId(topicId);
			post.setTopic(topic);
		}
		forumService.addPost(post);
		String targetUrl = "/boards/"+boardId+"/topics/"
				+ post.getTopic().getTopicId();
		return "redirect:"+targetUrl;
	}///boards/${board.boardId}/topics

	/**
	 * 删除主题
	 */
	@RequestMapping(value = "/boards/{boardId}/topics/{topicIds}", method = RequestMethod.DELETE)
	public String removeTopic(@PathVariable String topicIds,@PathVariable String boardId) {
		String[] arrIds = topicIds.split(",");
		for (int i = 0; i < arrIds.length; i++) {
			forumService.removeTopic(new Integer(arrIds[i]));
		}
		String targetUrl = "/boards/" + boardId;
		return "redirect:"+targetUrl;
	}

	/**
	 * 设置精华帖
	 */
	@RequestMapping(value = "/boards/{boardId}/topics/{topicIds}", method = RequestMethod.PATCH)
	public String makeDigestTopic(@PathVariable String topicIds,@PathVariable String boardId) {
		String[] arrIds = topicIds.split(",");
		for (int i = 0; i < arrIds.length; i++) {
			forumService.makeDigestTopic(new Integer(arrIds[i]));
		}
		String targetUrl = "/boards/" + boardId;
		return "redirect:"+targetUrl;
	}
}
